export type SeedListing = {
  sellerId: string;
  title: string;
  address: string;
  city: string;
  neighborhood: string;
  state: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  lotSqft: number | null;
  yearBuilt: number;
  propertyType: "house" | "condo" | "townhouse" | "apartment";
  style: string;
  description: string;
  promoted: boolean;
  photos: string[];
};

export const SEED_SELLERS = [
  {
    userId: "seed-seller-west",
    displayName: "Maya Chen",
    bio: "Listing homes across the West Coast.",
    avatarUrl: "/listings/avatar-1.jpg",
    role: "seller" as const,
  },
  {
    userId: "seed-seller-south",
    displayName: "Jordan Hale",
    bio: "Sunbelt specialist. Fast closings, honest photos.",
    avatarUrl: "/listings/avatar-2.jpg",
    role: "seller" as const,
  },
  {
    userId: "seed-seller-east",
    displayName: "Priya Raman",
    bio: "Brownstones, row houses, and city lofts.",
    avatarUrl: "/listings/avatar-4.jpg",
    role: "seller" as const,
  },
  {
    userId: "seed-seller-mid",
    displayName: "Evan Brooks",
    bio: "Midwest and mountain modern.",
    avatarUrl: "/listings/avatar-3.jpg",
    role: "seller" as const,
  },
];

export const SEED_AGENTS = [
  {
    userId: "seed-agent-1",
    displayName: "Sofia Alvarez",
    bio: "Verified agent — houses & townhomes, West + Southwest.",
    avatarUrl: "/listings/avatar-6.jpg",
    licenseNumber: "CA-DRE 02144819",
    coverageArea: "Los Angeles, San Diego, San Francisco, Phoenix",
    specialty: "house",
  },
  {
    userId: "seed-agent-2",
    displayName: "Marcus Webb",
    bio: "Verified agent — condos and urban lofts.",
    avatarUrl: "/listings/avatar-5.jpg",
    licenseNumber: "NY-DOS 1049281",
    coverageArea: "Brooklyn, Boston, Chicago, Miami, Atlanta",
    specialty: "condo",
  },
  {
    userId: "seed-agent-3",
    displayName: "Hannah Cole",
    bio: "Verified agent — any property type, national coverage.",
    avatarUrl: "/listings/avatar-1.jpg",
    licenseNumber: "TX-TREC 6784401",
    coverageArea: "Any",
    specialty: "any",
  },
];

export const SEED_LISTINGS: SeedListing[] = [
  {
    sellerId: "seed-seller-west",
    title: "Glass Canyon House",
    address: "418 Horizon Ridge",
    city: "Los Angeles",
    neighborhood: "Hollywood Hills",
    state: "CA",
    price: 2485000,
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 3280,
    lotSqft: 9200,
    yearBuilt: 2019,
    propertyType: "house",
    style: "modern",
    promoted: true,
    photos: ["/listings/01a.jpg", "/listings/01c.jpg", "/listings/05b.jpg"],
    description:
      "Floor-to-ceiling glass, a canyon-facing pool deck, and a kitchen built for long dinners. Quiet street, city lights after dark.",
  },
  {
    sellerId: "seed-seller-south",
    title: "East Austin Bungalow",
    address: "1104 Willow St",
    city: "Austin",
    neighborhood: "East Cesar Chavez",
    state: "TX",
    price: 625000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1680,
    lotSqft: 5400,
    yearBuilt: 1938,
    propertyType: "house",
    style: "craftsman",
    promoted: false,
    photos: ["/listings/02a.jpg", "/listings/02b.jpg", "/listings/02c.jpg"],
    description:
      "Restored bungalow with original millwork, a new chef kitchen, and a backyard big enough for a live oak and a long table.",
  },
  {
    sellerId: "seed-seller-east",
    title: "Cobble Hill Brownstone",
    address: "82 Warren Street",
    city: "Brooklyn",
    neighborhood: "Cobble Hill",
    state: "NY",
    price: 1849000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2860,
    lotSqft: 2100,
    yearBuilt: 1892,
    propertyType: "townhouse",
    style: "historic",
    promoted: true,
    photos: ["/listings/03a.jpg", "/listings/03b.jpg", "/listings/03c.jpg"],
    description:
      "Four-story brownstone with parlor-floor light, a garden apartment, and a restored stoop. Two blocks from the promenade.",
  },
  {
    sellerId: "seed-seller-south",
    title: "Aqua Vista Residence",
    address: "900 Brickell Key Dr #1804",
    city: "Miami",
    neighborhood: "Brickell",
    state: "FL",
    price: 890000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1420,
    lotSqft: null,
    yearBuilt: 2016,
    propertyType: "condo",
    style: "contemporary",
    promoted: false,
    photos: ["/listings/04a.jpg", "/listings/04b.jpg", "/listings/04c.jpg"],
    description:
      "Bay-facing condo with wraparound glass, resort amenities, and a walk to dinner. Turnkey and bright from every room.",
  },
  {
    sellerId: "seed-seller-mid",
    title: "Foothills Timber House",
    address: "27 Elk Path",
    city: "Denver",
    neighborhood: "Genesee",
    state: "CO",
    price: 1125000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2740,
    lotSqft: 18000,
    yearBuilt: 2014,
    propertyType: "house",
    style: "mountain modern",
    promoted: false,
    photos: ["/listings/05a.jpg", "/listings/05b.jpg", "/listings/05c.jpg"],
    description:
      "Timber-and-steel house tucked into the foothills. Walls of glass, a stone hearth, and trail access from the driveway.",
  },
  {
    sellerId: "seed-seller-west",
    title: "Ballard Craftsman",
    address: "6415 24th Ave NW",
    city: "Seattle",
    neighborhood: "Ballard",
    state: "WA",
    price: 975000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2140,
    lotSqft: 4000,
    yearBuilt: 1924,
    propertyType: "house",
    style: "craftsman",
    promoted: false,
    photos: ["/listings/06a.jpg", "/listings/06b.jpg", "/listings/06c.jpg"],
    description:
      "Classic Ballard lines with a new ADU-ready basement, fir floors, and a porch made for gray mornings and good coffee.",
  },
  {
    sellerId: "seed-seller-mid",
    title: "West Loop Loft",
    address: "1100 W Randolph St #6B",
    city: "Chicago",
    neighborhood: "West Loop",
    state: "IL",
    price: 540000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1380,
    lotSqft: null,
    yearBuilt: 2008,
    propertyType: "apartment",
    style: "industrial",
    promoted: false,
    photos: ["/listings/07a.jpg", "/listings/07c.jpg", "/listings/03b.jpg"],
    description:
      "Converted loft with 12-foot timber ceilings, a chef island, and elevator access. Fulton Market is downstairs.",
  },
  {
    sellerId: "seed-seller-west",
    title: "Noe Valley Victorian",
    address: "431 Castro Street",
    city: "San Francisco",
    neighborhood: "Noe Valley",
    state: "CA",
    price: 2895000,
    bedrooms: 5,
    bathrooms: 3.5,
    sqft: 3120,
    lotSqft: 2800,
    yearBuilt: 1906,
    propertyType: "house",
    style: "victorian",
    promoted: false,
    photos: ["/listings/08a.jpg", "/listings/08b.jpg", "/listings/01c.jpg"],
    description:
      "Painted lady with a modern spine: new systems, a south garden, and five bedrooms stacked above a sunny parlor.",
  },
  {
    sellerId: "seed-seller-south",
    title: "Arcadia Ranch",
    address: "7821 E Palm Lane",
    city: "Phoenix",
    neighborhood: "Arcadia",
    state: "AZ",
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1860,
    lotSqft: 10200,
    yearBuilt: 1962,
    propertyType: "house",
    style: "ranch",
    promoted: false,
    photos: ["/listings/09a.jpg", "/listings/09b.jpg", "/listings/09c.jpg"],
    description:
      "Low-slung ranch on a citrus lot. Terrazzo floors, a refreshed kitchen, and a pool that earns its keep all year.",
  },
  {
    sellerId: "seed-seller-west",
    title: "Alberta Midcentury",
    address: "4026 NE Alberta St",
    city: "Portland",
    neighborhood: "Concordia",
    state: "OR",
    price: 780000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1980,
    lotSqft: 5200,
    yearBuilt: 1958,
    propertyType: "house",
    style: "midcentury",
    promoted: false,
    photos: ["/listings/10a.jpg", "/listings/10b.jpg", "/listings/10c.jpg"],
    description:
      "Post-and-beam bones, clerestory light, and a kitchen that opens to a deck under firs. Alberta shops are a short walk.",
  },
  {
    sellerId: "seed-seller-south",
    title: "Inman Park Townhome",
    address: "219 North Highland Ave",
    city: "Atlanta",
    neighborhood: "Inman Park",
    state: "GA",
    price: 510000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1720,
    lotSqft: 1600,
    yearBuilt: 2018,
    propertyType: "townhouse",
    style: "contemporary",
    promoted: false,
    photos: ["/listings/11a.jpg", "/listings/11c.jpg", "/listings/14a.jpg"],
    description:
      "End-unit townhome with rooftop deck, garage parking, and beltline access. Quiet brick, loud kitchen.",
  },
  {
    sellerId: "seed-seller-east",
    title: "South End Row House",
    address: "54 West Newton St",
    city: "Boston",
    neighborhood: "South End",
    state: "MA",
    price: 1210000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2040,
    lotSqft: 1200,
    yearBuilt: 1874,
    propertyType: "townhouse",
    style: "historic",
    promoted: false,
    photos: ["/listings/12a.jpg", "/listings/12b.jpg", "/listings/12c.jpg"],
    description:
      "Bowfront row house with original plaster medallions, a garden patio, and a top-floor office that catches morning light.",
  },
  {
    sellerId: "seed-seller-south",
    title: "East Nashville Cottage",
    address: "908 Fatherland St",
    city: "Nashville",
    neighborhood: "East Nashville",
    state: "TN",
    price: 389000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1240,
    lotSqft: 6100,
    yearBuilt: 1947,
    propertyType: "house",
    style: "cottage",
    promoted: false,
    photos: ["/listings/13a.jpg", "/listings/13b.jpg", "/listings/13c.jpg"],
    description:
      "Shotgun cottage with a deep porch, a studio shed, and a kitchen that still feels like a Saturday. Walk to coffee and vinyl.",
  },
  {
    sellerId: "seed-seller-south",
    title: "Lakewood Family House",
    address: "3315 Abrams Road",
    city: "Dallas",
    neighborhood: "Lakewood",
    state: "TX",
    price: 565000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2480,
    lotSqft: 7800,
    yearBuilt: 1999,
    propertyType: "house",
    style: "traditional",
    promoted: false,
    photos: ["/listings/14a.jpg", "/listings/14b.jpg", "/listings/14c.jpg"],
    description:
      "Four bedrooms near the lake, a backyard that actually fits a game, and a kitchen island people gather around.",
  },
  {
    sellerId: "seed-seller-mid",
    title: "Chautauqua Cabin Modern",
    address: "12 Baseline Drive",
    city: "Boulder",
    neighborhood: "Chautauqua",
    state: "CO",
    price: 1350000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2080,
    lotSqft: 14000,
    yearBuilt: 2011,
    propertyType: "house",
    style: "mountain modern",
    promoted: true,
    photos: ["/listings/15a.jpg", "/listings/15b.jpg", "/listings/15c.jpg"],
    description:
      "A glass-and-cedar house under the Flatirons. Sleeps quiet, wakes with the trail. Two-car garage and a real mudroom.",
  },
  {
    sellerId: "seed-seller-west",
    title: "La Jolla Spanish",
    address: "7843 Eads Avenue",
    city: "San Diego",
    neighborhood: "La Jolla",
    state: "CA",
    price: 1650000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2620,
    lotSqft: 6500,
    yearBuilt: 1931,
    propertyType: "house",
    style: "spanish",
    promoted: false,
    photos: ["/listings/16a.jpg", "/listings/13a.jpg", "/listings/04a.jpg"],
    description:
      "White stucco, red tile, a courtyard fountain, and an ocean hint on the upper terrace. Restored without being precious.",
  },
  {
    sellerId: "seed-seller-mid",
    title: "Linden Hills Bungalow",
    address: "4316 Upton Ave S",
    city: "Minneapolis",
    neighborhood: "Linden Hills",
    state: "MN",
    price: 349000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1560,
    lotSqft: 5000,
    yearBuilt: 1922,
    propertyType: "house",
    style: "craftsman",
    promoted: false,
    photos: ["/listings/17b.jpg", "/listings/17c.jpg", "/listings/07a.jpg"],
    description:
      "Lake-adjacent bungalow with built-ins, a sun porch, and a kitchen that finally got the cabinets it deserved.",
  },
  {
    sellerId: "seed-seller-east",
    title: "South of Broad Single",
    address: "18 Legare Street",
    city: "Charleston",
    neighborhood: "South of Broad",
    state: "SC",
    price: 875000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2320,
    lotSqft: 3400,
    yearBuilt: 1854,
    propertyType: "house",
    style: "historic",
    promoted: false,
    photos: ["/listings/18a.jpg", "/listings/18b.jpg", "/listings/18c.jpg"],
    description:
      "A Charleston single with a piazza that catches the breeze, heart-pine floors, and a garden you will actually use.",
  },
];

const CITIES = [
  "Los Angeles",
  "Austin",
  "Brooklyn",
  "Miami",
  "Denver",
  "Seattle",
  "Chicago",
  "San Francisco",
  "Phoenix",
  "Portland",
  "Atlanta",
  "Boston",
  "Nashville",
  "Dallas",
  "Boulder",
  "San Diego",
  "Minneapolis",
  "Charleston",
] as const;

const CITY_BASE: Record<string, { price: number; count: number; psf: number }> = {
  "Los Angeles": { price: 1180000, count: 42, psf: 720 },
  Austin: { price: 610000, count: 55, psf: 340 },
  Brooklyn: { price: 1320000, count: 38, psf: 810 },
  Miami: { price: 740000, count: 61, psf: 520 },
  Denver: { price: 690000, count: 47, psf: 360 },
  Seattle: { price: 880000, count: 33, psf: 490 },
  Chicago: { price: 420000, count: 58, psf: 280 },
  "San Francisco": { price: 1640000, count: 22, psf: 980 },
  Phoenix: { price: 455000, count: 70, psf: 240 },
  Portland: { price: 620000, count: 29, psf: 330 },
  Atlanta: { price: 480000, count: 51, psf: 250 },
  Boston: { price: 910000, count: 27, psf: 620 },
  Nashville: { price: 520000, count: 44, psf: 290 },
  Dallas: { price: 470000, count: 66, psf: 230 },
  Boulder: { price: 980000, count: 14, psf: 540 },
  "San Diego": { price: 1020000, count: 31, psf: 650 },
  Minneapolis: { price: 365000, count: 40, psf: 210 },
  Charleston: { price: 640000, count: 19, psf: 360 },
};

export function buildMarketSnapshots() {
  const months: { month: string; drift: number }[] = [];
  const now = new Date();
  for (let i = 11; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    months.push({ month, drift: (11 - i) * 0.008 });
  }
  const rows: { city: string; month: string; avgPrice: number; listingCount: number; avgPsf: number }[] = [];
  for (const city of CITIES) {
    const base = CITY_BASE[city]!;
    for (const m of months) {
      const wobble = 1 + Math.sin(m.drift * 12 + city.length) * 0.02;
      rows.push({
        city,
        month: m.month,
        avgPrice: Math.round(base.price * (1 + m.drift) * wobble),
        listingCount: Math.max(8, Math.round(base.count * (0.9 + (m.drift % 0.2)))),
        avgPsf: Math.round(base.psf * (1 + m.drift * 0.7) * wobble),
      });
    }
  }
  return rows;
}
