/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppProRouteImport } from './routes/_app/pro'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSellRouteImport } from './routes/_app/sell'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppSuggestionsRouteImport } from './routes/_app/suggestions'
import { Route as AppVisitsRouteImport } from './routes/_app/visits'
import { Route as AppListingIdRouteImport } from './routes/_app/listing.$id'
import { Route as AppMessagesIdRouteImport } from './routes/_app/messages.$id'
import { Route as AppSellIdRouteImport } from './routes/_app/sell.$id'
import { Route as AppSellNewRouteImport } from './routes/_app/sell.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppProRoute = AppProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestionsRoute = AppSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AppRoute,
} as any)
const AppListingIdRoute = AppListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppSellIdRoute = AppSellIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSellRoute,
} as any)
const AppSellNewRoute = AppSellNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSellRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/agent': typeof AppAgentRoute
  '/discover': typeof AppDiscoverRoute
  '/favorites': typeof AppFavoritesRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/offers': typeof AppOffersRoute
  '/pro': typeof AppProRoute
  '/profile': typeof AppProfileRoute
  '/sell': typeof AppSellRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/suggestions': typeof AppSuggestionsRoute
  '/visits': typeof AppVisitsRoute
  '/listing/$id': typeof AppListingIdRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/sell/$id': typeof AppSellIdRoute
  '/sell/new': typeof AppSellNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/agent': typeof AppAgentRoute
  '/discover': typeof AppDiscoverRoute
  '/favorites': typeof AppFavoritesRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/offers': typeof AppOffersRoute
  '/pro': typeof AppProRoute
  '/profile': typeof AppProfileRoute
  '/sell': typeof AppSellRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/suggestions': typeof AppSuggestionsRoute
  '/visits': typeof AppVisitsRoute
  '/listing/$id': typeof AppListingIdRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/sell/$id': typeof AppSellIdRoute
  '/sell/new': typeof AppSellNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/pro': typeof AppProRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sell': typeof AppSellRouteWithChildren
  '/_app/stats': typeof AppStatsRoute
  '/_app/suggestions': typeof AppSuggestionsRoute
  '/_app/visits': typeof AppVisitsRoute
  '/_app/listing/$id': typeof AppListingIdRoute
  '/_app/messages/$id': typeof AppMessagesIdRoute
  '/_app/sell/$id': typeof AppSellIdRoute
  '/_app/sell/new': typeof AppSellNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/agent'
    | '/discover'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/offers'
    | '/pro'
    | '/profile'
    | '/sell'
    | '/stats'
    | '/suggestions'
    | '/visits'
    | '/listing/$id'
    | '/messages/$id'
    | '/sell/$id'
    | '/sell/new'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/agent'
    | '/discover'
    | '/favorites'
    | '/messages'
    | '/notifications'
    | '/offers'
    | '/pro'
    | '/profile'
    | '/sell'
    | '/stats'
    | '/suggestions'
    | '/visits'
    | '/listing/$id'
    | '/messages/$id'
    | '/sell/$id'
    | '/sell/new'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/agent'
    | '/_app/discover'
    | '/_app/favorites'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/offers'
    | '/_app/pro'
    | '/_app/profile'
    | '/_app/sell'
    | '/_app/stats'
    | '/_app/suggestions'
    | '/_app/visits'
    | '/_app/listing/$id'
    | '/_app/messages/$id'
    | '/_app/sell/$id'
    | '/_app/sell/new'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pro': {
      id: '/_app/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AppProRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sell': {
      id: '/_app/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suggestions': {
      id: '/_app/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof AppSuggestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits': {
      id: '/_app/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listing/$id': {
      id: '/_app/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof AppListingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$id': {
      id: '/_app/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/sell/$id': {
      id: '/_app/sell/$id'
      path: '/$id'
      fullPath: '/sell/$id'
      preLoaderRoute: typeof AppSellIdRouteImport
      parentRoute: typeof AppSellRoute
    }
    '/_app/sell/new': {
      id: '/_app/sell/new'
      path: '/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof AppSellNewRouteImport
      parentRoute: typeof AppSellRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppSellRouteChildren {
  AppSellIdRoute: typeof AppSellIdRoute
  AppSellNewRoute: typeof AppSellNewRoute
}

const AppSellRouteChildren: AppSellRouteChildren = {
  AppSellIdRoute: AppSellIdRoute,
  AppSellNewRoute: AppSellNewRoute,
}

const AppSellRouteWithChildren =
  AppSellRoute._addFileChildren(AppSellRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgentRoute: typeof AppAgentRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOffersRoute: typeof AppOffersRoute
  AppProRoute: typeof AppProRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSellRoute: typeof AppSellRouteWithChildren
  AppStatsRoute: typeof AppStatsRoute
  AppSuggestionsRoute: typeof AppSuggestionsRoute
  AppVisitsRoute: typeof AppVisitsRoute
  AppListingIdRoute: typeof AppListingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgentRoute: AppAgentRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOffersRoute: AppOffersRoute,
  AppProRoute: AppProRoute,
  AppProfileRoute: AppProfileRoute,
  AppSellRoute: AppSellRouteWithChildren,
  AppStatsRoute: AppStatsRoute,
  AppSuggestionsRoute: AppSuggestionsRoute,
  AppVisitsRoute: AppVisitsRoute,
  AppListingIdRoute: AppListingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
